# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Goffstown-Sports-App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Goffstown-Sports-App
  pod 'Firebase'
  pod 'Firebase/Database'
  pod 'Firebase/Core'
end
